import {
  Organization,
  Store,
  User,
  Category,
  Supplier,
  Product,
  InventoryLedgerEntry,
  SalesOrder,
  PurchaseOrder,
  Expense,
  ExpenseCategory,
  Customer,
  StockTransfer,
  Promotion,
  SystemAlert,
} from './types';

export const INITIAL_ORGANIZATIONS: Organization[] = [
  {
    id: 'org_01',
    name: 'SuperMart India Retail Ltd.',
    slug: 'supermart-india',
    subscription_tier: 'ENTERPRISE',
    subscription_status: 'ACTIVE',
    currency: 'INR',
    tax_rate: 12.0, // 12% GST average
    gstin: '29AAAAA1234A1Z5',
    logo_url: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=128&q=80',
    created_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'org_02',
    name: 'Aurelia Luxury Fashion India',
    slug: 'aurelia-fashion-india',
    subscription_tier: 'PROFESSIONAL',
    subscription_status: 'ACTIVE',
    currency: 'INR',
    tax_rate: 18.0, // 18% GST apparel & luxury
    gstin: '07BBBBB5678B1Z2',
    logo_url: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=128&q=80',
    created_at: '2026-02-01T00:00:00Z',
  },
  {
    id: 'org_03',
    name: 'Nexus Consumer Electronics India',
    slug: 'nexus-electronics-india',
    subscription_tier: 'ENTERPRISE',
    subscription_status: 'ACTIVE',
    currency: 'INR',
    tax_rate: 18.0, // 18% GST electronics
    gstin: '33CCCCC9012C1Z8',
    logo_url: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=128&q=80',
    created_at: '2026-02-10T00:00:00Z',
  },
];

export const INITIAL_STORES: Store[] = [
  // SuperMart India Stores
  {
    id: 'store_01',
    organization_id: 'org_01',
    name: 'SuperMart Bengaluru Indiranagar Flagship',
    code: 'SM-BLR-01',
    address: 'Plot 100, 100 Feet Road, HAL 2nd Stage, Indiranagar',
    city: 'Bengaluru',
    state: 'Karnataka',
    postal_code: '560038',
    gstin: '29AAAAA1234A1Z5',
    phone: '+91 80 2520 1199',
    email: 'indiranagar@supermart.in',
    is_active: true,
    created_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'store_02',
    organization_id: 'org_01',
    name: 'SuperMart Mumbai Bandra Express',
    code: 'SM-MUM-02',
    address: '24 Hill Road, Bandra West',
    city: 'Mumbai',
    state: 'Maharashtra',
    postal_code: '400050',
    gstin: '27AAAAA1234A1Z8',
    phone: '+91 22 2640 5544',
    email: 'bandra@supermart.in',
    is_active: true,
    created_at: '2026-01-20T00:00:00Z',
  },
  // Aurelia Store
  {
    id: 'store_03',
    organization_id: 'org_02',
    name: 'Aurelia South Ext Boutique',
    code: 'AF-DEL-01',
    address: 'G-14 South Extension Part-I',
    city: 'New Delhi',
    state: 'Delhi',
    postal_code: '110049',
    gstin: '07BBBBB5678B1Z2',
    phone: '+91 11 4160 8811',
    email: 'southext@aurelia.in',
    is_active: true,
    created_at: '2026-02-01T00:00:00Z',
  },
  // Nexus Store
  {
    id: 'store_04',
    organization_id: 'org_03',
    name: 'Nexus Tech Plaza Chennai',
    code: 'NX-CHN-01',
    address: '55 2nd Avenue, Anna Nagar',
    city: 'Chennai',
    state: 'Tamil Nadu',
    postal_code: '600040',
    gstin: '33CCCCC9012C1Z8',
    phone: '+91 44 2620 9900',
    email: 'annanagar@nexus.in',
    is_active: true,
    created_at: '2026-02-10T00:00:00Z',
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'user_super_admin',
    email: 'admin@retailpilot.ai',
    full_name: 'Super Administrator',
    role: 'SUPER_ADMIN',
    phone: '+91 99000 00001',
    is_active: true,
    last_login: '2026-08-24T18:00:00Z',
  },
  {
    id: 'user_owner',
    organization_id: 'org_01',
    email: 'rajesh.sharma@supermart.in',
    full_name: 'Rajesh Sharma (Executive Owner)',
    role: 'BUSINESS_OWNER',
    phone: '+91 98450 12345',
    is_active: true,
    last_login: '2026-08-24T17:30:00Z',
  },
  {
    id: 'user_manager',
    organization_id: 'org_01',
    store_id: 'store_01',
    email: 'priya.nair@supermart.in',
    full_name: 'Priya Nair (Store Manager)',
    role: 'STORE_MANAGER',
    phone: '+91 98451 23456',
    is_active: true,
    last_login: '2026-08-24T16:45:00Z',
  },
  {
    id: 'user_sales',
    organization_id: 'org_01',
    store_id: 'store_01',
    email: 'amit.verma@supermart.in',
    full_name: 'Amit Verma (Cashier & Sales)',
    role: 'SALES_STAFF',
    phone: '+91 98452 34567',
    is_active: true,
    last_login: '2026-08-24T16:00:00Z',
  },
  {
    id: 'user_inventory',
    organization_id: 'org_01',
    store_id: 'store_01',
    email: 'suresh.kumar@supermart.in',
    full_name: 'Suresh Kumar (Warehouse & GRN)',
    role: 'INVENTORY_STAFF',
    phone: '+91 98453 45678',
    is_active: true,
    last_login: '2026-08-24T15:15:00Z',
  },
  {
    id: 'user_cust_01',
    organization_id: 'org_01',
    email: 'ananya.iyer@gmail.com',
    full_name: 'Ananya Iyer (VIP Customer)',
    role: 'CUSTOMER',
    phone: '+91 98801 99223',
    is_active: true,
    last_login: '2026-08-24T14:10:00Z',
  },
];

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat_01',
    organization_id: 'org_01',
    name: 'Fresh Produce & Farm Direct',
    description: 'Farm-fresh organic fruits, vegetables, and daily staples',
  },
  {
    id: 'cat_02',
    organization_id: 'org_01',
    name: 'Dairy, Paneer & Cold Storage',
    description: 'Fresh milk, paneer, artisanal butter, and yogurts',
  },
  {
    id: 'cat_03',
    organization_id: 'org_01',
    name: 'Bakery & Fresh Breads',
    description: 'Artisanal sourdough loaves, whole wheat pav, and buns',
  },
  {
    id: 'cat_04',
    organization_id: 'org_01',
    name: 'Beverages, Tea & Artisanal Coffee',
    description: 'Specialty filter coffee roasts, Assam CTC tea, and tonics',
  },
  {
    id: 'cat_05',
    organization_id: 'org_01',
    name: 'Staples, Grains & Pulses',
    description: 'Super Basmati rice, Sharbati wheat atta, and unpolished dals',
  },
  {
    id: 'cat_06',
    organization_id: 'org_01',
    name: 'Eco-Friendly Home & Personal Care',
    description: 'Cold-pressed oils, eco cleaners, and natural detergents',
  },
  {
    id: 'cat_org2_01',
    organization_id: 'org_02',
    name: 'Luxury Silk Sarees & Ethnic Couture',
    description: 'Pure Banarasi Katan silk, Chanderi weaves, and gold zari',
  },
  {
    id: 'cat_org2_02',
    organization_id: 'org_02',
    name: 'Bridal & Bespoke Menswear',
    description: 'Handcrafted velvet lehengas, raw silk bandhgalas, and sherwanis',
  },
];

export const INITIAL_SUPPLIERS: Supplier[] = [
  {
    id: 'sup_01',
    organization_id: 'org_01',
    name: 'Karnataka Agro Produce Cooperative',
    contact_person: 'Venkatesh Murthy',
    email: 'supply@karnataka-agro.in',
    phone: '+91 80 2333 4455',
    address: 'APMC Yard, Yeshwanthpur, Bengaluru, KA 560022',
    gstin: '29AAACK1234B1Z3',
    credit_period_days: 30,
    outstanding_balance: 42500.0,
  },
  {
    id: 'sup_02',
    organization_id: 'org_01',
    name: 'Amul Dairy Cooperative Federation',
    contact_person: 'Bhavin Patel',
    email: 'distribution@amul.coop',
    phone: '+91 26 9225 8500',
    address: 'Anand Dairy Road, Anand, Gujarat 388001',
    gstin: '24AAACA9876C1Z9',
    credit_period_days: 15,
    outstanding_balance: 28600.0,
  },
  {
    id: 'sup_03',
    organization_id: 'org_01',
    name: 'Himalayan Organic Estates & Roasters',
    contact_person: 'Anand Negi',
    email: 'orders@himalayan-coffee.in',
    phone: '+91 17 7280 1200',
    address: 'Estate 12, The Mall Road, Shimla, HP 171001',
    gstin: '02AAACH5678D1Z1',
    credit_period_days: 45,
    outstanding_balance: 14200.0,
  },
  {
    id: 'sup_org2_01',
    organization_id: 'org_02',
    name: 'Varanasi Master Weavers Cooperative',
    contact_person: 'Pandit Ramcharan Shastri',
    email: 'craft@varanasi-weavers.in',
    phone: '+91 54 2250 8899',
    address: 'Chowk Silk Market, Varanasi, UP 221001',
    gstin: '09AAACV4433D1Z9',
    credit_period_days: 45,
    outstanding_balance: 85000.0,
  },
  {
    id: 'sup_org2_02',
    organization_id: 'org_02',
    name: 'Jaipur Royal Zardozi Heritage Guild',
    contact_person: 'Mahendra Singh Shekhawat',
    email: 'bespoke@jaipur-zardozi.in',
    phone: '+91 14 1260 7744',
    address: 'Johari Bazaar, Pink City, Jaipur, RJ 302003',
    gstin: '08AAACJ7788E1Z4',
    credit_period_days: 30,
    outstanding_balance: 120000.0,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod_01',
    organization_id: 'org_01',
    category_id: 'cat_01',
    category_name: 'Fresh Produce & Farm Direct',
    supplier_id: 'sup_01',
    supplier_name: 'Karnataka Agro Produce Cooperative',
    sku: 'ORG-APL-01',
    barcode: '8901234000012',
    name: 'Himachal Royal Delicious Apples (1 kg)',
    description: 'Crisp, hand-picked pesticide-free Kinnaur apples',
    unit_cost: 120.0,
    selling_price: 180.0,
    reorder_point: 30,
    reorder_quantity: 50,
    is_active: true,
  },
  {
    id: 'prod_02',
    organization_id: 'org_01',
    category_id: 'cat_01',
    category_name: 'Fresh Produce & Farm Direct',
    supplier_id: 'sup_01',
    supplier_name: 'Karnataka Agro Produce Cooperative',
    sku: 'ORG-MNG-02',
    barcode: '8901234000029',
    name: 'Ratnagiri Alphonso Mango Pulp (850g Tin)',
    description: '100% pure GI-tagged Ratnagiri Alphonso pulp, no added sugar',
    unit_cost: 240.0,
    selling_price: 360.0,
    reorder_point: 15,
    reorder_quantity: 30,
    is_active: true,
  },
  {
    id: 'prod_03',
    organization_id: 'org_01',
    category_id: 'cat_02',
    category_name: 'Dairy, Paneer & Cold Storage',
    supplier_id: 'sup_02',
    supplier_name: 'Amul Dairy Cooperative Federation',
    sku: 'DRY-MLK-03',
    barcode: '8901234000036',
    name: 'Amul Gold Pasteurised Whole Milk (1 Litre Pouch)',
    description: 'Full cream milk with 6.0% fat, vitamin fortified',
    unit_cost: 54.0,
    selling_price: 68.0,
    reorder_point: 50,
    reorder_quantity: 100,
    is_active: true,
  },
  {
    id: 'prod_04',
    organization_id: 'org_01',
    category_id: 'cat_02',
    category_name: 'Dairy, Paneer & Cold Storage',
    supplier_id: 'sup_02',
    supplier_name: 'Amul Dairy Cooperative Federation',
    sku: 'DRY-PNR-04',
    barcode: '8901234000043',
    name: 'Fresh Malai Paneer Block (200g)',
    description: 'Vacuum packed fresh cottage cheese, high protein',
    unit_cost: 95.0,
    selling_price: 135.0,
    reorder_point: 25,
    reorder_quantity: 60,
    is_active: true,
  },
  {
    id: 'prod_05',
    organization_id: 'org_01',
    category_id: 'cat_03',
    category_name: 'Bakery & Fresh Breads',
    supplier_id: 'sup_03',
    supplier_name: 'Himalayan Organic Estates & Roasters',
    sku: 'BAK-SRD-05',
    barcode: '8901234000050',
    name: 'Artisan Sourdough Country Loaf (400g)',
    description: 'Naturally fermented sourdough baked fresh daily with wild yeast',
    unit_cost: 90.0,
    selling_price: 160.0,
    reorder_point: 15,
    reorder_quantity: 25,
    is_active: true,
  },
  {
    id: 'prod_06',
    organization_id: 'org_01',
    category_id: 'cat_04',
    category_name: 'Beverages, Tea & Artisanal Coffee',
    supplier_id: 'sup_03',
    supplier_name: 'Himalayan Organic Estates & Roasters',
    sku: 'BEV-CBR-06',
    barcode: '8901234000067',
    name: 'Madras Specialty Filter Coffee Roast (500g)',
    description: '80:20 Arabica Plantation A and Chicory blend, aromatic roast',
    unit_cost: 260.0,
    selling_price: 380.0,
    reorder_point: 10,
    reorder_quantity: 30,
    is_active: true,
  },
  {
    id: 'prod_07',
    organization_id: 'org_01',
    category_id: 'cat_05',
    category_name: 'Staples, Grains & Pulses',
    supplier_id: 'sup_01',
    supplier_name: 'Karnataka Agro Produce Cooperative',
    sku: 'STP-RCE-07',
    barcode: '8901234000074',
    name: 'Daawat Super Basmati Rice (5 kg Bag)',
    description: 'Aged long-grain aromatic Royal Basmati rice',
    unit_cost: 380.0,
    selling_price: 520.0,
    reorder_point: 20,
    reorder_quantity: 40,
    is_active: true,
  },
  {
    id: 'prod_08',
    organization_id: 'org_01',
    category_id: 'cat_05',
    category_name: 'Staples, Grains & Pulses',
    supplier_id: 'sup_01',
    supplier_name: 'Karnataka Agro Produce Cooperative',
    sku: 'STP-ATA-08',
    barcode: '8901234000081',
    name: 'Aashirvaad Select Sharbati Atta (5 kg Bag)',
    description: '100% MP Sharbati wheat whole grain stone ground atta',
    unit_cost: 240.0,
    selling_price: 325.0,
    reorder_point: 20,
    reorder_quantity: 40,
    is_active: true,
  },
  {
    id: 'prod_09',
    organization_id: 'org_01',
    category_id: 'cat_04',
    category_name: 'Beverages, Tea & Artisanal Coffee',
    supplier_id: 'sup_03',
    supplier_name: 'Himalayan Organic Estates & Roasters',
    sku: 'BEV-TEA-09',
    barcode: '8901234000098',
    name: 'Wagh Bakri Premium CTC Spiced Chai (1 kg Pack)',
    description: 'Assam upper-garden strong CTC blend with cardamom and ginger',
    unit_cost: 360.0,
    selling_price: 490.0,
    reorder_point: 15,
    reorder_quantity: 30,
    is_active: true,
  },
  {
    id: 'prod_10',
    organization_id: 'org_01',
    category_id: 'cat_06',
    category_name: 'Eco-Friendly Home & Personal Care',
    supplier_id: 'sup_01',
    supplier_name: 'Karnataka Agro Produce Cooperative',
    sku: 'ECO-OIL-10',
    barcode: '8901234000104',
    name: 'Cold Pressed Organic Virgin Coconut Oil (500 ml Glass Bottle)',
    description: 'Wood-pressed pure edible coconut oil from Pollachi farms',
    unit_cost: 210.0,
    selling_price: 310.0,
    reorder_point: 15,
    reorder_quantity: 30,
    is_active: true,
  },
  {
    id: 'prod_11',
    organization_id: 'org_01',
    category_id: 'cat_04',
    category_name: 'Beverages, Tea & Artisanal Coffee',
    supplier_id: 'sup_03',
    supplier_name: 'Himalayan Organic Estates & Roasters',
    sku: 'BEV-TRF-11',
    barcode: '8901234000111',
    name: 'Kashmiri Saffron & Truffle Infused Tonic (Case of 24)',
    description: 'Gourmet sparkling botanical water infused with genuine Mongra saffron',
    unit_cost: 1850.0,
    selling_price: 2800.0,
    reorder_point: 5,
    reorder_quantity: 10,
    is_active: true,
  },
  // --- Org 02: Aurelia Luxury Fashion India Products ---
  {
    id: 'prod_org2_01',
    organization_id: 'org_02',
    category_id: 'cat_org2_01',
    category_name: 'Luxury Silk Sarees & Ethnic Couture',
    supplier_id: 'sup_org2_01',
    supplier_name: 'Varanasi Master Weavers Cooperative',
    sku: 'AUR-SAR-01',
    barcode: '8902001000014',
    name: 'Banarasi Pure Katan Silk Zari Saree (Crimson Red)',
    description: 'Handwoven pure mulberry silk with antique gold electroplated zari motifs',
    unit_cost: 18500.0,
    selling_price: 32000.0,
    reorder_point: 5,
    reorder_quantity: 10,
    is_active: true,
  },
  {
    id: 'prod_org2_02',
    organization_id: 'org_02',
    category_id: 'cat_org2_02',
    category_name: 'Bridal & Bespoke Menswear',
    supplier_id: 'sup_org2_02',
    supplier_name: 'Jaipur Royal Zardozi Heritage Guild',
    sku: 'AUR-SHR-02',
    barcode: '8902001000021',
    name: 'Handcrafted Raw Silk Bandhgala Sherwani (Royal Navy)',
    description: 'Hand-tailored raw silk with intricate dabka and zardozi threadwork',
    unit_cost: 24000.0,
    selling_price: 45000.0,
    reorder_point: 3,
    reorder_quantity: 8,
    is_active: true,
  },
  {
    id: 'prod_org2_03',
    organization_id: 'org_02',
    category_id: 'cat_org2_02',
    category_name: 'Bridal & Bespoke Menswear',
    supplier_id: 'sup_org2_02',
    supplier_name: 'Jaipur Royal Zardozi Heritage Guild',
    sku: 'AUR-LHG-03',
    barcode: '8902001000038',
    name: 'Embroidered Velvet Bridal Lehenga Set (Deep Emerald)',
    description: 'Bespoke hand-embroidered velvet lehenga featuring semi-precious stone embellishments',
    unit_cost: 65000.0,
    selling_price: 115000.0,
    reorder_point: 2,
    reorder_quantity: 5,
    is_active: true,
  },
  {
    id: 'prod_org2_04',
    organization_id: 'org_02',
    category_id: 'cat_org2_01',
    category_name: 'Luxury Silk Sarees & Ethnic Couture',
    supplier_id: 'sup_org2_01',
    supplier_name: 'Varanasi Master Weavers Cooperative',
    sku: 'AUR-KRT-04',
    barcode: '8902001000045',
    name: 'Chanderi Handwoven Festive Kurta Ensemble (Ivory Gold)',
    description: 'Lightweight handloom Chanderi silk kurta with pure cotton silk churidar',
    unit_cost: 6500.0,
    selling_price: 12800.0,
    reorder_point: 8,
    reorder_quantity: 15,
    is_active: true,
  },
];

export const INITIAL_LEDGER_ENTRIES: InventoryLedgerEntry[] = [
  // Store 01 (Bengaluru) - Initial Opening Stock
  {
    id: 'led_01',
    organization_id: 'org_01',
    store_id: 'store_01',
    product_id: 'prod_01',
    product_name: 'Himachal Royal Delicious Apples (1 kg)',
    sku: 'ORG-APL-01',
    movement_type: 'OPENING_STOCK',
    quantity_change: 85,
    unit_cost: 120.0,
    total_cost: 10200.0,
    reason: 'Initial fiscal month store opening balance',
    created_at: '2026-08-01T08:00:00Z',
  },
  {
    id: 'led_02',
    organization_id: 'org_01',
    store_id: 'store_01',
    product_id: 'prod_02',
    product_name: 'Ratnagiri Alphonso Mango Pulp (850g Tin)',
    sku: 'ORG-MNG-02',
    movement_type: 'OPENING_STOCK',
    quantity_change: 12, // Low stock: 12 <= 15
    unit_cost: 240.0,
    total_cost: 2880.0,
    reason: 'Store opening balance count',
    created_at: '2026-08-01T08:00:00Z',
  },
  {
    id: 'led_03',
    organization_id: 'org_01',
    store_id: 'store_01',
    product_id: 'prod_03',
    product_name: 'Amul Gold Pasteurised Whole Milk (1 Litre Pouch)',
    sku: 'DRY-MLK-03',
    movement_type: 'OPENING_STOCK',
    quantity_change: 180,
    unit_cost: 54.0,
    total_cost: 9720.0,
    reason: 'Morning cold chain delivery intake',
    created_at: '2026-08-01T08:00:00Z',
  },
  {
    id: 'led_04',
    organization_id: 'org_01',
    store_id: 'store_01',
    product_id: 'prod_04',
    product_name: 'Fresh Malai Paneer Block (200g)',
    sku: 'DRY-PNR-04',
    movement_type: 'OPENING_STOCK',
    quantity_change: 110,
    unit_cost: 95.0,
    total_cost: 10450.0,
    reason: 'Dairy opening stock intake',
    created_at: '2026-08-01T08:00:00Z',
  },
  {
    id: 'led_05',
    organization_id: 'org_01',
    store_id: 'store_01',
    product_id: 'prod_05',
    product_name: 'Artisan Sourdough Country Loaf (400g)',
    sku: 'BAK-SRD-05',
    movement_type: 'OPENING_STOCK',
    quantity_change: 28,
    unit_cost: 90.0,
    total_cost: 2520.0,
    reason: 'Fresh bakery intake',
    created_at: '2026-08-01T08:00:00Z',
  },
  {
    id: 'led_06',
    organization_id: 'org_01',
    store_id: 'store_01',
    product_id: 'prod_06',
    product_name: 'Madras Specialty Filter Coffee Roast (500g)',
    sku: 'BEV-CBR-06',
    movement_type: 'OPENING_STOCK',
    quantity_change: 8, // Low stock: 8 <= 10
    unit_cost: 260.0,
    total_cost: 2080.0,
    reason: 'Coffee bar inventory count',
    created_at: '2026-08-01T08:00:00Z',
  },
  {
    id: 'led_07',
    organization_id: 'org_01',
    store_id: 'store_01',
    product_id: 'prod_07',
    product_name: 'Daawat Super Basmati Rice (5 kg Bag)',
    sku: 'STP-RCE-07',
    movement_type: 'OPENING_STOCK',
    quantity_change: 65,
    unit_cost: 380.0,
    total_cost: 24700.0,
    reason: 'Grains bay intake',
    created_at: '2026-08-01T08:00:00Z',
  },
  {
    id: 'led_08',
    organization_id: 'org_01',
    store_id: 'store_01',
    product_id: 'prod_08',
    product_name: 'Aashirvaad Select Sharbati Atta (5 kg Bag)',
    sku: 'STP-ATA-08',
    movement_type: 'OPENING_STOCK',
    quantity_change: 55,
    unit_cost: 240.0,
    total_cost: 13200.0,
    reason: 'Staples pallet intake',
    created_at: '2026-08-01T08:00:00Z',
  },
  {
    id: 'led_09',
    organization_id: 'org_01',
    store_id: 'store_01',
    product_id: 'prod_09',
    product_name: 'Wagh Bakri Premium CTC Spiced Chai (1 kg Pack)',
    sku: 'BEV-TEA-09',
    movement_type: 'OPENING_STOCK',
    quantity_change: 40,
    unit_cost: 360.0,
    total_cost: 14400.0,
    reason: 'Beverages intake',
    created_at: '2026-08-01T08:00:00Z',
  },
  {
    id: 'led_10',
    organization_id: 'org_01',
    store_id: 'store_01',
    product_id: 'prod_10',
    product_name: 'Cold Pressed Organic Virgin Coconut Oil (500 ml Glass Bottle)',
    sku: 'ECO-OIL-10',
    movement_type: 'OPENING_STOCK',
    quantity_change: 35,
    unit_cost: 210.0,
    total_cost: 7350.0,
    reason: 'Personal care intake',
    created_at: '2026-08-01T08:00:00Z',
  },
  {
    id: 'led_11',
    organization_id: 'org_01',
    store_id: 'store_01',
    product_id: 'prod_11',
    product_name: 'Kashmiri Saffron & Truffle Infused Tonic (Case of 24)',
    sku: 'BEV-TRF-11',
    movement_type: 'OPENING_STOCK',
    quantity_change: 48, // Dead stock (48 * 1850 = 88,800.00 capital)
    unit_cost: 1850.0,
    total_cost: 88800.0,
    reason: 'Specialty high-tier seasonal inventory intake (>75 days stagnant)',
    created_at: '2026-06-01T08:00:00Z',
  },
  // --- Org 02: Aurelia Luxury Fashion India Opening Stock ---
  {
    id: 'led_org2_01',
    organization_id: 'org_02',
    store_id: 'store_03',
    product_id: 'prod_org2_01',
    product_name: 'Banarasi Pure Katan Silk Zari Saree (Crimson Red)',
    sku: 'AUR-SAR-01',
    movement_type: 'OPENING_STOCK',
    quantity_change: 25,
    unit_cost: 18500.0,
    total_cost: 462500.0,
    reason: 'Luxury boutique opening stock intake',
    created_at: '2026-08-01T08:00:00Z',
  },
  {
    id: 'led_org2_02',
    organization_id: 'org_02',
    store_id: 'store_03',
    product_id: 'prod_org2_02',
    product_name: 'Handcrafted Raw Silk Bandhgala Sherwani (Royal Navy)',
    sku: 'AUR-SHR-02',
    movement_type: 'OPENING_STOCK',
    quantity_change: 15,
    unit_cost: 24000.0,
    total_cost: 360000.0,
    reason: 'Bespoke menswear intake',
    created_at: '2026-08-01T08:00:00Z',
  },
  {
    id: 'led_org2_03',
    organization_id: 'org_02',
    store_id: 'store_03',
    product_id: 'prod_org2_03',
    product_name: 'Embroidered Velvet Bridal Lehenga Set (Deep Emerald)',
    sku: 'AUR-LHG-03',
    movement_type: 'OPENING_STOCK',
    quantity_change: 8,
    unit_cost: 65000.0,
    total_cost: 520000.0,
    reason: 'Bridal couture collection intake',
    created_at: '2026-08-01T08:00:00Z',
  },
  {
    id: 'led_org2_04',
    organization_id: 'org_02',
    store_id: 'store_03',
    product_id: 'prod_org2_04',
    product_name: 'Chanderi Handwoven Festive Kurta Ensemble (Ivory Gold)',
    sku: 'AUR-KRT-04',
    movement_type: 'OPENING_STOCK',
    quantity_change: 40,
    unit_cost: 6500.0,
    total_cost: 260000.0,
    reason: 'Festive ready-to-wear intake',
    created_at: '2026-08-01T08:00:00Z',
  },
];

export const INITIAL_EXPENSE_CATEGORIES: ExpenseCategory[] = [
  { id: 'exp_cat_01', organization_id: 'org_01', name: 'Commercial Rent & Facility' },
  { id: 'exp_cat_02', organization_id: 'org_01', name: 'Staff Payroll & Benefits' },
  { id: 'exp_cat_03', organization_id: 'org_01', name: 'Electricity & Cold Storage Utilities' },
  { id: 'exp_cat_04', organization_id: 'org_01', name: 'Software, POS & Cloud SaaS' },
  { id: 'exp_cat_05', organization_id: 'org_01', name: 'Store Packaging & Logistics' },
  { id: 'exp_cat_org2_01', organization_id: 'org_02', name: 'Luxury Showroom Lease & Ambiance' },
  { id: 'exp_cat_org2_02', organization_id: 'org_02', name: 'Master Tailors & Fashion Stylists Payroll' },
  { id: 'exp_cat_org2_03', organization_id: 'org_02', name: 'Showroom Power & Visual Merchandising' },
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'exp_01',
    organization_id: 'org_01',
    store_id: 'store_01',
    category_id: 'exp_cat_01',
    category_name: 'Commercial Rent & Facility',
    title: 'Indiranagar Prime Retail Space Monthly Lease',
    amount: 75000.0,
    expense_date: '2026-08-01',
    logged_by: 'user_manager',
    notes: 'Paid via RTGS to landlord for August 2026',
    created_at: '2026-08-01T10:00:00Z',
  },
  {
    id: 'exp_02',
    organization_id: 'org_01',
    store_id: 'store_01',
    category_id: 'exp_cat_02',
    category_name: 'Staff Payroll & Benefits',
    title: 'Store Floor Staff & Cashier Monthly Payroll',
    amount: 42000.0,
    expense_date: '2026-08-05',
    logged_by: 'user_owner',
    notes: 'Direct salary disbursements for 4 staff members',
    created_at: '2026-08-05T11:00:00Z',
  },
  {
    id: 'exp_03',
    organization_id: 'org_01',
    store_id: 'store_01',
    category_id: 'exp_cat_03',
    category_name: 'Electricity & Cold Storage Utilities',
    title: 'BESCOM Commercial Power & Walk-in Chiller Electricity',
    amount: 16500.0,
    expense_date: '2026-08-10',
    logged_by: 'user_manager',
    notes: 'Commercial meter power tariff settlement',
    created_at: '2026-08-10T14:30:00Z',
  },
  {
    id: 'exp_04',
    organization_id: 'org_01',
    store_id: 'store_01',
    category_id: 'exp_cat_04',
    category_name: 'Software, POS & Cloud SaaS',
    title: 'RetailPilot AI Cloud SaaS & POS Hardware Terminal Subscriptions',
    amount: 4500.0,
    expense_date: '2026-08-12',
    logged_by: 'user_manager',
    notes: 'Multi-store cloud sync and backup',
    created_at: '2026-08-12T09:15:00Z',
  },
  {
    id: 'exp_05',
    organization_id: 'org_01',
    store_id: 'store_01',
    category_id: 'exp_cat_05',
    category_name: 'Store Packaging & Logistics',
    title: 'Bio-Degradable Bags, Thermal Paper Rolls & Sanitization',
    amount: 7000.0,
    expense_date: '2026-08-15',
    logged_by: 'user_inventory',
    notes: 'Monthly consumable supplies replenishment',
    created_at: '2026-08-15T16:00:00Z',
  },
  // --- Org 02: Aurelia Luxury Fashion Expenses ---
  {
    id: 'exp_org2_01',
    organization_id: 'org_02',
    store_id: 'store_03',
    category_id: 'exp_cat_org2_01',
    category_name: 'Luxury Showroom Lease & Ambiance',
    title: 'DLF Emporio Luxury Showroom Monthly Lease',
    amount: 180000.0,
    expense_date: '2026-08-01',
    logged_by: 'user_org2_owner',
    notes: 'August 2026 prime retail space lease',
    created_at: '2026-08-01T10:00:00Z',
  },
  {
    id: 'exp_org2_02',
    organization_id: 'org_02',
    store_id: 'store_03',
    category_id: 'exp_cat_org2_02',
    category_name: 'Master Tailors & Fashion Stylists Payroll',
    title: 'Couture Master Artisans & Stylists Monthly Payroll',
    amount: 95000.0,
    expense_date: '2026-08-05',
    logged_by: 'user_org2_owner',
    notes: 'Specialist bespoke tailoring team salaries',
    created_at: '2026-08-05T11:00:00Z',
  },
  {
    id: 'exp_org2_03',
    organization_id: 'org_02',
    store_id: 'store_03',
    category_id: 'exp_cat_org2_03',
    category_name: 'Showroom Power & Visual Merchandising',
    title: 'Chandelier Illumination & Climate Control Power Settlement',
    amount: 22000.0,
    expense_date: '2026-08-10',
    logged_by: 'user_org2_owner',
    notes: 'High-amperage boutique aesthetic lighting',
    created_at: '2026-08-10T14:30:00Z',
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust_01',
    organization_id: 'org_01',
    name: 'Ananya Iyer',
    email: 'ananya.iyer@gmail.com',
    phone: '+91 98801 99223',
    loyalty_points: 1250,
    total_spend: 34800.0,
    created_at: '2026-02-14T00:00:00Z',
  },
  {
    id: 'cust_02',
    organization_id: 'org_01',
    name: 'Rohan Deshmukh',
    email: 'rohan.deshmukh@outlook.com',
    phone: '+91 98200 44556',
    loyalty_points: 840,
    total_spend: 21600.0,
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'cust_03',
    organization_id: 'org_01',
    name: 'Dr. Meenakshi Sundaram',
    email: 'meenakshi.s@manipal.edu',
    phone: '+91 98440 77889',
    loyalty_points: 2100,
    total_spend: 58400.0,
    created_at: '2026-01-20T00:00:00Z',
  },
];

// Helper to construct fully reconciled Sales Order with 100% exact math
export function createReconciledSalesOrder(params: {
  id: string;
  invoice_number: string;
  customer_id?: string;
  customer_name?: string;
  discount_amount: number;
  payment_method: 'CASH' | 'CREDIT_CARD' | 'DEBIT_CARD' | 'UPI' | 'SPLIT';
  ref_txn: string;
  items: { product: Product; quantity: number }[];
  created_at: string;
}): SalesOrder {
  const salesItems = params.items.map((it, idx) => {
    const subtotal = Number((it.quantity * it.product.selling_price).toFixed(2));
    const cogs = Number((it.quantity * it.product.unit_cost).toFixed(2));
    return {
      id: `${params.id}_item_${idx + 1}`,
      sales_order_id: params.id,
      product_id: it.product.id,
      product_name: it.product.name,
      sku: it.product.sku,
      quantity: it.quantity,
      unit_cost: it.product.unit_cost,
      unit_price: it.product.selling_price,
      subtotal,
      cogs,
    };
  });

  const subtotal = Number(salesItems.reduce((sum, item) => sum + item.subtotal, 0).toFixed(2));
  const cogs_amount = Number(salesItems.reduce((sum, item) => sum + item.cogs, 0).toFixed(2));
  const discount_amount = Number(params.discount_amount.toFixed(2));
  const taxable_amount = Number((subtotal - discount_amount).toFixed(2));
  const tax_amount = Number((taxable_amount * 0.12).toFixed(2)); // 12% GST
  const cgst_amount = Number((tax_amount / 2).toFixed(2));
  const sgst_amount = Number((tax_amount - cgst_amount).toFixed(2));
  const total_amount = Number((taxable_amount + tax_amount).toFixed(2));

  return {
    id: params.id,
    organization_id: 'org_01',
    store_id: 'store_01',
    store_name: 'SuperMart Bengaluru Indiranagar Flagship',
    customer_id: params.customer_id,
    customer_name: params.customer_name,
    cashier_id: 'user_sales',
    cashier_name: 'Amit Verma',
    invoice_number: params.invoice_number,
    subtotal,
    taxable_amount,
    tax_amount,
    cgst_amount,
    sgst_amount,
    discount_amount,
    total_amount,
    cogs_amount,
    payments: [
      {
        id: `pay_${params.id}`,
        sales_order_id: params.id,
        payment_method: params.payment_method,
        amount: total_amount,
        reference_transaction_id: params.ref_txn,
        created_at: params.created_at,
      },
    ],
    items: salesItems,
    status: 'COMPLETED',
    created_at: params.created_at,
  };
}

// Map products for easy creation
export const P = {
  apples: INITIAL_PRODUCTS[0],
  mango: INITIAL_PRODUCTS[1],
  milk: INITIAL_PRODUCTS[2],
  paneer: INITIAL_PRODUCTS[3],
  bread: INITIAL_PRODUCTS[4],
  coffee: INITIAL_PRODUCTS[5],
  rice: INITIAL_PRODUCTS[6],
  atta: INITIAL_PRODUCTS[7],
  tea: INITIAL_PRODUCTS[8],
  oil: INITIAL_PRODUCTS[9],
  tonic: INITIAL_PRODUCTS[10],
};

// Seed realistic high-volume historical sales orders with 100% item-level line traceability
export const INITIAL_SALES_ORDERS: SalesOrder[] = [
  // 1. Walk-in Family Grocery Basket (INV-202608-1001)
  createReconciledSalesOrder({
    id: 'ord_1001',
    invoice_number: 'INV-202608-1001',
    customer_id: 'cust_01',
    customer_name: 'Ananya Iyer',
    discount_amount: 0.0,
    payment_method: 'UPI',
    ref_txn: 'UPI-RAZORPAY-99201948',
    items: [
      { product: P.apples, quantity: 3 },
      { product: P.milk, quantity: 4 },
      { product: P.paneer, quantity: 2 },
      { product: P.rice, quantity: 1 },
      { product: P.atta, quantity: 1 },
    ],
    created_at: '2026-08-20T10:15:00Z',
  }),

  // 2. Artisanal Breakfast & Tea Basket (INV-202608-1002)
  createReconciledSalesOrder({
    id: 'ord_1002',
    invoice_number: 'INV-202608-1002',
    customer_id: 'cust_02',
    customer_name: 'Rohan Deshmukh',
    discount_amount: 150.0,
    payment_method: 'CREDIT_CARD',
    ref_txn: 'TXN-HDFC-CC-448201',
    items: [
      { product: P.coffee, quantity: 2 },
      { product: P.bread, quantity: 2 },
      { product: P.mango, quantity: 2 },
      { product: P.tea, quantity: 1 },
    ],
    created_at: '2026-08-20T11:45:00Z',
  }),

  // 3. Weekly Premium Pantry Replenishment (INV-202608-1003)
  createReconciledSalesOrder({
    id: 'ord_1003',
    invoice_number: 'INV-202608-1003',
    customer_id: 'cust_03',
    customer_name: 'Dr. Meenakshi Sundaram',
    discount_amount: 100.0,
    payment_method: 'SPLIT',
    ref_txn: 'SPLIT-UPI-2000.00-CASH-1861.76',
    items: [
      { product: P.rice, quantity: 3 },
      { product: P.atta, quantity: 2 },
      { product: P.oil, quantity: 3 },
      { product: P.milk, quantity: 6 },
    ],
    created_at: '2026-08-21T14:20:00Z',
  }),

  // 4. Daily Morning Fresh Produce Rush (INV-202608-1004)
  createReconciledSalesOrder({
    id: 'ord_1004',
    invoice_number: 'INV-202608-1004',
    customer_id: 'cust_01',
    customer_name: 'Ananya Iyer',
    discount_amount: 0.0,
    payment_method: 'CASH',
    ref_txn: 'CASH-TILL-REG-01',
    items: [
      { product: P.apples, quantity: 4 },
      { product: P.paneer, quantity: 3 },
      { product: P.milk, quantity: 5 },
      { product: P.bread, quantity: 1 },
    ],
    created_at: '2026-08-22T09:10:00Z',
  }),

  // 5. High-Value Bulk Gourmet Hamper (INV-202608-1005)
  createReconciledSalesOrder({
    id: 'ord_1005',
    invoice_number: 'INV-202608-1005',
    customer_id: 'cust_03',
    customer_name: 'Dr. Meenakshi Sundaram',
    discount_amount: 250.0,
    payment_method: 'CREDIT_CARD',
    ref_txn: 'TXN-ICICI-CC-990142',
    items: [
      { product: P.coffee, quantity: 4 },
      { product: P.tea, quantity: 3 },
      { product: P.mango, quantity: 3 },
      { product: P.oil, quantity: 2 },
      { product: P.rice, quantity: 2 },
    ],
    created_at: '2026-08-23T18:30:00Z',
  }),

  // 6-24. Discrete Daily Store Orders (Aug 1 - Aug 19, 2026) - Calibrated to exact ₹13,53,880 Org 01 Gross Sales
  ...Array.from({ length: 19 }).map((_, idx) => {
    const day = idx + 1;
    const dayStr = day < 10 ? `0${day}` : `${day}`;
    const isOdd = day % 2 === 1;

    const riceQty = day === 1 ? 64 : 65;
    const teaQty = (day === 2 || day === 3) ? 1 : 2;

    const items = [
      { product: P.rice, quantity: riceQty },
      { product: P.atta, quantity: 40 },
      { product: P.tonic, quantity: 4 },
      { product: P.milk, quantity: 80 },
      { product: P.apples, quantity: 20 },
      { product: P.coffee, quantity: 5 },
      { product: P.tea, quantity: teaQty },
      { product: P.oil, quantity: 2 },
    ];

    const orderId = `ord_${1006 + idx}`;
    const invNum = `INV-202608-${1006 + idx}`;
    const paymentMethods = ['UPI', 'CREDIT_CARD', 'CASH', 'DEBIT_CARD'];
    const pMethod = paymentMethods[idx % paymentMethods.length] as any;

    return createReconciledSalesOrder({
      id: orderId,
      invoice_number: invNum,
      customer_id: isOdd ? 'cust_01' : 'cust_02',
      customer_name: isOdd ? 'Ananya Iyer' : 'Rohan Deshmukh',
      discount_amount: 0.0,
      payment_method: pMethod,
      ref_txn: `${pMethod}-SETTLE-202608${dayStr}`,
      items,
      created_at: `2026-08-${dayStr}T14:30:00Z`,
    });
  }),
  // --- Org 02: Aurelia Luxury Fashion India Discrete Sales Orders ---
  {
    id: 'ord_org2_101',
    organization_id: 'org_02',
    store_id: 'store_03',
    customer_id: 'cust_03',
    customer_name: 'Meera Kapoor',
    invoice_number: 'INV-AUR-202608-01',
    subtotal: 160000.0,
    taxable_amount: 160000.0,
    tax_amount: 28800.0,
    cgst_amount: 14400.0,
    sgst_amount: 14400.0,
    discount_amount: 0.0,
    total_amount: 188800.0,
    cogs_amount: 89000.0,
    status: 'COMPLETED',
    created_at: '2026-08-10T16:00:00Z',
    items: [
      {
        id: 'ord_org2_101_item_1',
        sales_order_id: 'ord_org2_101',
        product_id: 'prod_org2_03',
        product_name: 'Embroidered Velvet Bridal Lehenga Set (Deep Emerald)',
        sku: 'AUR-LHG-03',
        quantity: 1,
        unit_cost: 65000.0,
        unit_price: 115000.0,
        subtotal: 115000.0,
        cogs: 65000.0,
      },
      {
        id: 'ord_org2_101_item_2',
        sales_order_id: 'ord_org2_101',
        product_id: 'prod_org2_02',
        product_name: 'Handcrafted Raw Silk Bandhgala Sherwani (Royal Navy)',
        sku: 'AUR-SHR-02',
        quantity: 1,
        unit_cost: 24000.0,
        unit_price: 45000.0,
        subtotal: 45000.0,
        cogs: 24000.0,
      },
    ],
    payments: [
      {
        id: 'pay_org2_101',
        sales_order_id: 'ord_org2_101',
        payment_method: 'CREDIT_CARD',
        amount: 188800.0,
        reference_transaction_id: 'HDFC-POS-AUR101',
        created_at: '2026-08-10T16:00:00Z',
      },
    ],
  },
  {
    id: 'ord_org2_102',
    organization_id: 'org_02',
    store_id: 'store_03',
    customer_id: 'cust_03',
    customer_name: 'Meera Kapoor',
    invoice_number: 'INV-AUR-202608-02',
    subtotal: 64000.0,
    taxable_amount: 64000.0,
    tax_amount: 11520.0,
    cgst_amount: 5760.0,
    sgst_amount: 5760.0,
    discount_amount: 0.0,
    total_amount: 75520.0,
    cogs_amount: 37000.0,
    status: 'COMPLETED',
    created_at: '2026-08-14T18:30:00Z',
    items: [
      {
        id: 'ord_org2_102_item_1',
        sales_order_id: 'ord_org2_102',
        product_id: 'prod_org2_01',
        product_name: 'Banarasi Pure Katan Silk Zari Saree (Crimson Red)',
        sku: 'AUR-SAR-01',
        quantity: 2,
        unit_cost: 18500.0,
        unit_price: 32000.0,
        subtotal: 64000.0,
        cogs: 37000.0,
      },
    ],
    payments: [
      {
        id: 'pay_org2_102',
        sales_order_id: 'ord_org2_102',
        payment_method: 'UPI',
        amount: 75520.0,
        reference_transaction_id: 'UPI-AUR102',
        created_at: '2026-08-14T18:30:00Z',
      },
    ],
  },
  {
    id: 'ord_org2_103',
    organization_id: 'org_02',
    store_id: 'store_03',
    customer_id: 'cust_03',
    customer_name: 'Meera Kapoor',
    invoice_number: 'INV-AUR-202608-03',
    subtotal: 25600.0,
    taxable_amount: 25600.0,
    tax_amount: 4608.0,
    cgst_amount: 2304.0,
    sgst_amount: 2304.0,
    discount_amount: 0.0,
    total_amount: 30208.0,
    cogs_amount: 13000.0,
    status: 'COMPLETED',
    created_at: '2026-08-18T12:15:00Z',
    items: [
      {
        id: 'ord_org2_103_item_1',
        sales_order_id: 'ord_org2_103',
        product_id: 'prod_org2_04',
        product_name: 'Chanderi Handwoven Festive Kurta Ensemble (Ivory Gold)',
        sku: 'AUR-KRT-04',
        quantity: 2,
        unit_cost: 6500.0,
        unit_price: 12800.0,
        subtotal: 25600.0,
        cogs: 13000.0,
      },
    ],
    payments: [
      {
        id: 'pay_org2_103',
        sales_order_id: 'ord_org2_103',
        payment_method: 'DEBIT_CARD',
        amount: 30208.0,
        reference_transaction_id: 'POS-AUR103',
        created_at: '2026-08-18T12:15:00Z',
      },
    ],
  },
];

export const INITIAL_PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: 'po_01',
    organization_id: 'org_01',
    store_id: 'store_01',
    supplier_id: 'sup_01',
    supplier_name: 'Karnataka Agro Produce Cooperative',
    po_number: 'PO-202608-001',
    status: 'SENT',
    total_amount: 42500.0,
    payment_status: 'PENDING',
    payment_due_date: '2026-08-25', // Urgent <48h window!
    items: [
      {
        id: 'po_item_01',
        purchase_order_id: 'po_01',
        product_id: 'prod_01',
        product_name: 'Himachal Royal Delicious Apples (1 kg)',
        sku: 'ORG-APL-01',
        quantity_ordered: 150,
        quantity_received: 0,
        unit_cost: 120.0,
        subtotal: 18000.0,
      },
      {
        id: 'po_item_02',
        purchase_order_id: 'po_01',
        product_id: 'prod_07',
        product_name: 'Daawat Super Basmati Rice (5 kg Bag)',
        sku: 'STP-RCE-07',
        quantity_ordered: 50,
        quantity_received: 0,
        unit_cost: 380.0,
        subtotal: 19000.0,
      },
      {
        id: 'po_item_03',
        purchase_order_id: 'po_01',
        product_id: 'prod_10',
        product_name: 'Cold Pressed Organic Virgin Coconut Oil (500 ml Glass Bottle)',
        sku: 'ECO-OIL-10',
        quantity_ordered: 26,
        quantity_received: 0,
        unit_cost: 210.0,
        subtotal: 5500.0, // (adjusted 26 * 210 = 5460 + 40 buffer)
      },
    ],
    notes: 'Urgent harvest intake for weekend retail traffic',
    created_at: '2026-08-18T11:00:00Z',
    updated_at: '2026-08-18T11:00:00Z',
  },
  {
    id: 'po_02',
    organization_id: 'org_01',
    store_id: 'store_01',
    supplier_id: 'sup_02',
    supplier_name: 'Amul Dairy Cooperative Federation',
    po_number: 'PO-202608-002',
    status: 'RECEIVED',
    total_amount: 28600.0,
    payment_status: 'OVERDUE',
    payment_due_date: '2026-08-20', // Overdue!
    items: [
      {
        id: 'po_item_04',
        purchase_order_id: 'po_02',
        product_id: 'prod_03',
        product_name: 'Amul Gold Pasteurised Whole Milk (1 Litre Pouch)',
        sku: 'DRY-MLK-03',
        quantity_ordered: 300,
        quantity_received: 300,
        unit_cost: 54.0,
        subtotal: 16200.0,
      },
      {
        id: 'po_item_05',
        purchase_order_id: 'po_02',
        product_id: 'prod_04',
        product_name: 'Fresh Malai Paneer Block (200g)',
        sku: 'DRY-PNR-04',
        quantity_ordered: 130,
        quantity_received: 130,
        unit_cost: 95.0,
        subtotal: 12400.0, // (adjusted 130*95=12350+50)
      },
    ],
    notes: 'Chilled cold-chain delivery GRN verified and accepted',
    created_at: '2026-08-05T08:00:00Z',
    updated_at: '2026-08-06T10:00:00Z',
  },
  {
    id: 'po_03',
    organization_id: 'org_01',
    store_id: 'store_01',
    supplier_id: 'sup_03',
    supplier_name: 'Himalayan Organic Estates & Roasters',
    po_number: 'PO-202608-003',
    status: 'SENT',
    total_amount: 18200.0,
    payment_status: 'PENDING',
    payment_due_date: '2026-09-15',
    items: [
      {
        id: 'po_item_06',
        purchase_order_id: 'po_03',
        product_id: 'prod_06',
        product_name: 'Madras Specialty Filter Coffee Roast (500g)',
        sku: 'BEV-CBR-06',
        quantity_ordered: 70,
        quantity_received: 0,
        unit_cost: 260.0,
        subtotal: 18200.0,
      },
    ],
    notes: 'Plantation blend replenishment',
    created_at: '2026-08-15T15:00:00Z',
    updated_at: '2026-08-15T15:00:00Z',
  },
];

export const INITIAL_TRANSFERS: StockTransfer[] = [
  {
    id: 'trf_01',
    organization_id: 'org_01',
    transfer_number: 'TRF-202608-001',
    source_store_id: 'store_01',
    source_store_name: 'SuperMart Bengaluru Indiranagar Flagship',
    destination_store_id: 'store_02',
    destination_store_name: 'SuperMart Mumbai Bandra Express',
    status: 'DISPATCHED',
    requested_by: 'user_manager',
    dispatched_by: 'user_inventory',
    notes: 'Inter-branch stock rebalancing of high-velocity Basmati rice',
    items: [
      {
        id: 'trf_item_01',
        transfer_id: 'trf_01',
        product_id: 'prod_07',
        product_name: 'Daawat Super Basmati Rice (5 kg Bag)',
        sku: 'STP-RCE-07',
        quantity_requested: 25,
        quantity_sent: 25,
        quantity_received: 0,
      },
    ],
    created_at: '2026-08-21T09:00:00Z',
    updated_at: '2026-08-21T11:30:00Z',
  },
];
export const INITIAL_STOCK_TRANSFERS = INITIAL_TRANSFERS;

export const INITIAL_PROMOTIONS: Promotion[] = [
  {
    id: 'promo_01',
    organization_id: 'org_01',
    title: 'VIP Weekend Harvest Savings',
    discount_percentage: 10,
    target_tier: 'VIP',
    valid_until: '2026-08-31',
    code: 'HARVEST10',
  },
  {
    id: 'promo_02',
    organization_id: 'org_01',
    title: 'Stagnant Stock Liquidation Flash Sale',
    discount_percentage: 30,
    target_tier: 'ALL',
    valid_until: '2026-08-31',
    code: 'FLASH30',
  },
];

export const INITIAL_ALERTS: SystemAlert[] = [
  {
    id: 'alt_01',
    organization_id: 'org_01',
    store_id: 'store_01',
    alert_type: 'LOW_STOCK',
    severity: 'WARNING',
    title: 'Low Stock Trigger: 2 High-Velocity SKUs Below Reorder Point',
    message: 'Ratnagiri Alphonso Mango Pulp (12 units rem, threshold 15) and Madras Filter Coffee (8 units rem, threshold 10) require urgent replenishment PO.',
    is_read: false,
    action_url: 'https://retail-ai-pilot.vercel.app/login',
    created_at: '2026-08-24T06:00:00Z',
  },
  {
    id: 'alt_02',
    organization_id: 'org_01',
    store_id: 'store_01',
    alert_type: 'DEAD_STOCK',
    severity: 'WARNING',
    title: 'Dead Stock Audit: ₹88,800.00 Stagnant Capital Detected',
    message: 'Kashmiri Saffron & Truffle Infused Tonic (48 cases) has logged zero sales in >75 days. Autonomous liquidation discount plan generated.',
    is_read: false,
    action_url: 'https://retail-ai-pilot.vercel.app/login',
    created_at: '2026-08-24T00:01:00Z',
  },
  {
    id: 'alt_03',
    organization_id: 'org_01',
    store_id: 'store_01',
    alert_type: 'SUPPLIER_PAYMENT',
    severity: 'CRITICAL',
    title: 'Payment Escalation: Karnataka Agro Produce (₹42,500.00 Due in <24h)',
    message: 'PO-202608-001 payment due by 2026-08-25. Escalate to Accounts / Store Manager to preserve 30-day net credit lines.',
    is_read: false,
    action_url: 'https://retail-ai-pilot.vercel.app/login',
    created_at: '2026-08-24T07:30:00Z',
  },
];
