import {
  Organization,
  Store,
  User,
  Category,
  Supplier,
  Product,
  InventoryLedgerEntry,
  SalesOrder,
  PurchaseOrder,
  Expense,
  ExpenseCategory,
  Customer,
  StockTransfer,
  Promotion,
  SystemAlert,
} from './types';

export const INITIAL_ORGANIZATIONS: Organization[] = [
  {
    id: 'org_01',
    name: 'SuperMart Global Retail',
    slug: 'supermart-global',
    subscription_tier: 'ENTERPRISE',
    subscription_status: 'ACTIVE',
    currency: 'USD',
    tax_rate: 8.25,
    logo_url: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=128&q=80',
    created_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'org_02',
    name: 'Aurelia Luxury Fashion',
    slug: 'aurelia-fashion',
    subscription_tier: 'PROFESSIONAL',
    subscription_status: 'ACTIVE',
    currency: 'USD',
    tax_rate: 8.875,
    logo_url: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=128&q=80',
    created_at: '2026-02-01T00:00:00Z',
  },
  {
    id: 'org_03',
    name: 'Nexus Consumer Electronics',
    slug: 'nexus-electronics',
    subscription_tier: 'ENTERPRISE',
    subscription_status: 'ACTIVE',
    currency: 'USD',
    tax_rate: 7.5,
    logo_url: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=128&q=80',
    created_at: '2026-02-10T00:00:00Z',
  },
];

export const INITIAL_STORES: Store[] = [
  // SuperMart Stores
  {
    id: 'store_01',
    organization_id: 'org_01',
    name: 'SuperMart Downtown Flagship',
    code: 'SM-DT-01',
    address: '100 Broadway Ave',
    city: 'New York',
    phone: '+1 (212) 555-0199',
    email: 'downtown@supermart.com',
    is_active: true,
    created_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'store_02',
    organization_id: 'org_01',
    name: 'SuperMart Midtown Express',
    code: 'SM-MT-02',
    address: '450 Lexington Ave',
    city: 'New York',
    phone: '+1 (212) 555-0144',
    email: 'midtown@supermart.com',
    is_active: true,
    created_at: '2026-01-20T00:00:00Z',
  },
  // Aurelia Stores
  {
    id: 'store_03',
    organization_id: 'org_02',
    name: 'Aurelia Soho Boutique',
    code: 'AF-SH-01',
    address: '520 Broadway',
    city: 'New York',
    phone: '+1 (212) 555-0811',
    email: 'soho@aurelia.com',
    is_active: true,
    created_at: '2026-02-01T00:00:00Z',
  },
  // Nexus Stores
  {
    id: 'store_04',
    organization_id: 'org_03',
    name: 'Nexus Tech Plaza',
    code: 'NX-TP-01',
    address: '777 Market St',
    city: 'San Francisco',
    phone: '+1 (415) 555-0320',
    email: 'sfplaza@nexustech.io',
    is_active: true,
    created_at: '2026-02-10T00:00:00Z',
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'user_superadmin',
    email: 'superadmin@retailpilot.ai',
    full_name: 'Elena Rostova (Global Admin)',
    role: 'SUPER_ADMIN',
    is_active: true,
    last_login: '2026-08-21T06:30:00Z',
  },
  {
    id: 'user_owner',
    organization_id: 'org_01',
    store_id: 'store_01',
    email: 'owner@supermart.com',
    full_name: 'Marcus Sterling (Executive Owner)',
    role: 'BUSINESS_OWNER',
    is_active: true,
    last_login: '2026-08-21T06:15:00Z',
  },
  {
    id: 'user_manager',
    organization_id: 'org_01',
    store_id: 'store_01',
    email: 'manager@supermart.com',
    full_name: 'Sarah Chen (Store Manager)',
    role: 'STORE_MANAGER',
    is_active: true,
    last_login: '2026-08-21T06:45:00Z',
  },
  {
    id: 'user_sales',
    organization_id: 'org_01',
    store_id: 'store_01',
    email: 'sales@supermart.com',
    full_name: 'David Miller (Lead Cashier)',
    role: 'SALES_STAFF',
    is_active: true,
    last_login: '2026-08-21T06:50:00Z',
  },
  {
    id: 'user_inventory',
    organization_id: 'org_01',
    store_id: 'store_01',
    email: 'inventory@supermart.com',
    full_name: 'Raj Patel (Stock & GRN Lead)',
    role: 'INVENTORY_STAFF',
    is_active: true,
    last_login: '2026-08-21T06:40:00Z',
  },
  {
    id: 'user_customer',
    organization_id: 'org_01',
    email: 'customer@gmail.com',
    full_name: 'Alice Johnson (VIP Club Member)',
    role: 'CUSTOMER',
    is_active: true,
    last_login: '2026-08-20T19:20:00Z',
  },
];

export const INITIAL_CATEGORIES: Category[] = [
  // SuperMart categories
  { id: 'cat_01', organization_id: 'org_01', name: 'Fresh Produce & Organic', description: 'Fresh fruits and farm vegetables' },
  { id: 'cat_02', organization_id: 'org_01', name: 'Dairy & Plant Milks', description: 'Refrigerated milk, cheese, yogurt' },
  { id: 'cat_03', organization_id: 'org_01', name: 'Artisan Bakery & Snacks', description: 'Breads, pastries and organic snacks' },
  { id: 'cat_04', organization_id: 'org_01', name: 'Beverages & Cold Brews', description: 'Coffee, sparkling juices and teas' },
  { id: 'cat_05', organization_id: 'org_01', name: 'Household & Eco Essentials', description: 'Sustainable cleaners and paper goods' },
  // Aurelia categories
  { id: 'cat_06', organization_id: 'org_02', name: 'Outerwear & Coats', description: 'Designer coats and wool jackets' },
  { id: 'cat_07', organization_id: 'org_02', name: 'Silk & Knit Tops', description: 'Premium silk blouses and cashmere sweaters' },
  // Nexus categories
  { id: 'cat_08', organization_id: 'org_03', name: 'Smart Audio & ANC', description: 'Wireless headphones and spatial soundbars' },
  { id: 'cat_09', organization_id: 'org_03', name: 'Fast Chargers & Power', description: 'GaN chargers, docks and power banks' },
];

export const INITIAL_SUPPLIERS: Supplier[] = [
  // SuperMart Suppliers
  {
    id: 'sup_01',
    organization_id: 'org_01',
    name: 'Valley Organics Farm Direct',
    contact_person: 'Robert Hayes',
    email: 'orders@valleyorganics.com',
    phone: '+1 (555) 234-8901',
    address: '89 Farm Creek Rd, Hudson Valley, NY',
    credit_period_days: 30,
    outstanding_balance: 14250.00,
  },
  {
    id: 'sup_02',
    organization_id: 'org_01',
    name: 'Meadow Gold Dairy Cooperative',
    contact_person: 'Clara Oswald',
    email: 'accounts@meadowgold.com',
    phone: '+1 (555) 345-6789',
    address: '12 Pasture Lane, Lancaster, PA',
    credit_period_days: 15,
    outstanding_balance: 8320.50,
  },
  {
    id: 'sup_03',
    organization_id: 'org_01',
    name: 'Artisan Roast & Beverage Co.',
    contact_person: 'Mateo Rossi',
    email: 'billing@artisanroast.com',
    phone: '+1 (555) 456-7890',
    address: '304 Roastery Row, Brooklyn, NY',
    credit_period_days: 30,
    outstanding_balance: 5190.00,
  },
  {
    id: 'sup_04',
    organization_id: 'org_01',
    name: 'EcoClean Essentials Inc.',
    contact_person: 'Hannah Schmidt',
    email: 'supply@ecoclean.com',
    phone: '+1 (555) 567-8901',
    address: '77 Green Tech Blvd, Newark, NJ',
    credit_period_days: 45,
    outstanding_balance: 12400.00,
  },
  // Aurelia Supplier
  {
    id: 'sup_05',
    organization_id: 'org_02',
    name: 'Milano Fabric & Tailoring Group',
    contact_person: 'Gianni Romano',
    email: 'commerciale@milanotextile.it',
    phone: '+39 02 5550 9182',
    address: 'Via Montenapoleone 18, Milan, Italy',
    credit_period_days: 60,
    outstanding_balance: 38500.00,
  },
  // Nexus Supplier
  {
    id: 'sup_06',
    organization_id: 'org_03',
    name: 'Silicon Dynamics Micro Devices',
    contact_person: 'Kevin Zhao',
    email: 'distrib@silicondynamics.io',
    phone: '+1 (408) 555-8933',
    address: '2200 Semiconductor Pkwy, San Jose, CA',
    credit_period_days: 30,
    outstanding_balance: 64200.00,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  // SuperMart Products (org_01)
  {
    id: 'prod_01',
    organization_id: 'org_01',
    category_id: 'cat_01',
    category_name: 'Fresh Produce & Organic',
    supplier_id: 'sup_01',
    supplier_name: 'Valley Organics Farm Direct',
    sku: 'ORG-APL-01',
    barcode: '890100100011',
    name: 'Organic Honeycrisp Apples (1 lb)',
    description: 'Crisp, sweet, locally sourced organic grade A apples',
    unit_cost: 1.80,
    selling_price: 3.99,
    reorder_point: 25,
    reorder_quantity: 100,
    is_active: true,
  },
  {
    id: 'prod_02',
    organization_id: 'org_01',
    category_id: 'cat_01',
    category_name: 'Fresh Produce & Organic',
    supplier_id: 'sup_01',
    supplier_name: 'Valley Organics Farm Direct',
    sku: 'ORG-AVC-02',
    barcode: '890100100028',
    name: 'Organic Hass Avocados (Pack of 4)',
    description: 'Fresh ready-to-eat organic Hass avocados',
    unit_cost: 2.20,
    selling_price: 4.99,
    reorder_point: 20,
    reorder_quantity: 80,
    is_active: true,
  },
  {
    id: 'prod_03',
    organization_id: 'org_01',
    category_id: 'cat_02',
    category_name: 'Dairy & Plant Milks',
    supplier_id: 'sup_02',
    supplier_name: 'Meadow Gold Dairy Cooperative',
    sku: 'DRY-MLK-03',
    barcode: '890100100035',
    name: 'Grass-Fed Whole Milk 1 Gallon',
    description: 'Pasture-raised, non-homogenized whole milk with cream top',
    unit_cost: 3.10,
    selling_price: 5.89,
    reorder_point: 15,
    reorder_quantity: 60,
    is_active: true,
  },
  {
    id: 'prod_04',
    organization_id: 'org_01',
    category_id: 'cat_02',
    category_name: 'Dairy & Plant Milks',
    supplier_id: 'sup_02',
    supplier_name: 'Meadow Gold Dairy Cooperative',
    sku: 'DRY-OAT-04',
    barcode: '890100100042',
    name: 'Barista Organic Oat Milk (32 oz)',
    description: 'Creamy barista blend oat milk for latte craft',
    unit_cost: 2.40,
    selling_price: 4.79,
    reorder_point: 30,
    reorder_quantity: 120,
    is_active: true,
  },
  {
    id: 'prod_05',
    organization_id: 'org_01',
    category_id: 'cat_03',
    category_name: 'Artisan Bakery & Snacks',
    supplier_id: 'sup_03',
    supplier_name: 'Artisan Roast & Beverage Co.',
    sku: 'BAK-SRD-05',
    barcode: '890100100059',
    name: 'San Francisco Sourdough Boule',
    description: 'Slow-fermented 36hr sourdough rustic bread',
    unit_cost: 2.50,
    selling_price: 6.49,
    reorder_point: 12,
    reorder_quantity: 40,
    is_active: true,
  },
  {
    id: 'prod_06',
    organization_id: 'org_01',
    category_id: 'cat_04',
    category_name: 'Beverages & Cold Brews',
    supplier_id: 'sup_03',
    supplier_name: 'Artisan Roast & Beverage Co.',
    sku: 'BEV-CBR-06',
    barcode: '890100100066',
    name: 'Nitro Cold Brew Coffee Can (12 oz)',
    description: 'Single-origin Ethiopian nitro infused cold brew',
    unit_cost: 1.90,
    selling_price: 4.29,
    reorder_point: 40,
    reorder_quantity: 150,
    is_active: true,
  },
  {
    id: 'prod_07',
    organization_id: 'org_01',
    category_id: 'cat_05',
    category_name: 'Household & Eco Essentials',
    supplier_id: 'sup_04',
    supplier_name: 'EcoClean Essentials Inc.',
    sku: 'ECO-DSH-07',
    barcode: '890100100073',
    name: 'Zero-Waste Lavender Dish Soap (16 oz)',
    description: 'Plant-powered biodegradable concentrated dish soap',
    unit_cost: 3.50,
    selling_price: 7.99,
    reorder_point: 18,
    reorder_quantity: 50,
    is_active: true,
  },
  {
    id: 'prod_08',
    organization_id: 'org_01',
    category_id: 'cat_05',
    category_name: 'Household & Eco Essentials',
    supplier_id: 'sup_04',
    supplier_name: 'EcoClean Essentials Inc.',
    sku: 'ECO-DET-08',
    barcode: '890100100080',
    name: 'Ultra Eco Laundry Detergent Sheets (60 ct)',
    description: 'Dissolvable plastic-free laundry detergent sheets',
    unit_cost: 6.20,
    selling_price: 14.99,
    reorder_point: 15,
    reorder_quantity: 40,
    is_active: true,
  },
  // Dead Stock Candidate for SuperMart (0 sales in 75 days, high cost)
  {
    id: 'prod_09',
    organization_id: 'org_01',
    category_id: 'cat_04',
    category_name: 'Beverages & Cold Brews',
    supplier_id: 'sup_03',
    supplier_name: 'Artisan Roast & Beverage Co.',
    sku: 'BEV-TRF-09',
    barcode: '890100100097',
    name: 'Imported White Truffle Infused Tonic (Case of 12)',
    description: 'Specialty luxury sparkling tonic water with Italian white truffle aroma',
    unit_cost: 38.00,
    selling_price: 74.99,
    reorder_point: 5,
    reorder_quantity: 20,
    is_active: true,
  },
  // Aurelia Products (org_02)
  {
    id: 'prod_10',
    organization_id: 'org_02',
    category_id: 'cat_06',
    category_name: 'Outerwear & Coats',
    supplier_id: 'sup_05',
    supplier_name: 'Milano Fabric & Tailoring Group',
    sku: 'FSH-COAT-01',
    barcode: '890200100018',
    name: 'Italian Cashmere Belted Trench Coat',
    description: 'Handcrafted camel cashmere trench coat with horn buttons',
    unit_cost: 280.00,
    selling_price: 695.00,
    reorder_point: 8,
    reorder_quantity: 20,
    is_active: true,
  },
  // Nexus Products (org_03)
  {
    id: 'prod_11',
    organization_id: 'org_03',
    category_id: 'cat_08',
    category_name: 'Smart Audio & ANC',
    supplier_id: 'sup_06',
    supplier_name: 'Silicon Dynamics Micro Devices',
    sku: 'TECH-ANC-01',
    barcode: '890300100015',
    name: 'AeroPulse Hybrid ANC Wireless Headphones',
    description: 'High-res lossless audio with 40-hour battery and spatial audio tracking',
    unit_cost: 110.00,
    selling_price: 249.99,
    reorder_point: 10,
    reorder_quantity: 30,
    is_active: true,
  },
];

// Initial Immutable Ledger Entries generating live stock balances
export const INITIAL_LEDGER_ENTRIES: InventoryLedgerEntry[] = [
  // SuperMart Downtown (store_01)
  {
    id: 'led_001',
    organization_id: 'org_01',
    store_id: 'store_01',
    store_name: 'SuperMart Downtown Flagship',
    product_id: 'prod_01',
    product_name: 'Organic Honeycrisp Apples (1 lb)',
    sku: 'ORG-APL-01',
    movement_type: 'OPENING_STOCK',
    quantity_change: 85,
    unit_cost: 1.80,
    total_cost: 153.00,
    reason: 'Initial fiscal year store balance initialization',
    created_at: '2026-08-01T08:00:00Z',
  },
  {
    id: 'led_002',
    organization_id: 'org_01',
    store_id: 'store_01',
    store_name: 'SuperMart Downtown Flagship',
    product_id: 'prod_02',
    product_name: 'Organic Hass Avocados (Pack of 4)',
    sku: 'ORG-AVC-02',
    movement_type: 'OPENING_STOCK',
    quantity_change: 12, // LOW STOCK! Reorder point is 20
    unit_cost: 2.20,
    total_cost: 26.40,
    reason: 'Store opening count',
    created_at: '2026-08-01T08:00:00Z',
  },
  {
    id: 'led_003',
    organization_id: 'org_01',
    store_id: 'store_01',
    store_name: 'SuperMart Downtown Flagship',
    product_id: 'prod_03',
    product_name: 'Grass-Fed Whole Milk 1 Gallon',
    sku: 'DRY-MLK-03',
    movement_type: 'OPENING_STOCK',
    quantity_change: 45,
    unit_cost: 3.10,
    total_cost: 139.50,
    reason: 'Store opening balance',
    created_at: '2026-08-01T08:00:00Z',
  },
  {
    id: 'led_004',
    organization_id: 'org_01',
    store_id: 'store_01',
    store_name: 'SuperMart Downtown Flagship',
    product_id: 'prod_04',
    product_name: 'Barista Organic Oat Milk (32 oz)',
    sku: 'DRY-OAT-04',
    movement_type: 'OPENING_STOCK',
    quantity_change: 90,
    unit_cost: 2.40,
    total_cost: 216.00,
    reason: 'Store opening balance',
    created_at: '2026-08-01T08:00:00Z',
  },
  {
    id: 'led_005',
    organization_id: 'org_01',
    store_id: 'store_01',
    store_name: 'SuperMart Downtown Flagship',
    product_id: 'prod_05',
    product_name: 'San Francisco Sourdough Boule',
    sku: 'BAK-SRD-05',
    movement_type: 'OPENING_STOCK',
    quantity_change: 30,
    unit_cost: 2.50,
    total_cost: 75.00,
    reason: 'Bakery fresh intake',
    created_at: '2026-08-01T08:00:00Z',
  },
  {
    id: 'led_006',
    organization_id: 'org_01',
    store_id: 'store_01',
    store_name: 'SuperMart Downtown Flagship',
    product_id: 'prod_06',
    product_name: 'Nitro Cold Brew Coffee Can (12 oz)',
    sku: 'BEV-CBR-06',
    movement_type: 'OPENING_STOCK',
    quantity_change: 8, // CRITICAL LOW STOCK! Reorder point is 40
    unit_cost: 1.90,
    total_cost: 15.20,
    reason: 'Opening stock count',
    created_at: '2026-08-01T08:00:00Z',
  },
  {
    id: 'led_007',
    organization_id: 'org_01',
    store_id: 'store_01',
    store_name: 'SuperMart Downtown Flagship',
    product_id: 'prod_07',
    product_name: 'Zero-Waste Lavender Dish Soap (16 oz)',
    sku: 'ECO-DSH-07',
    movement_type: 'OPENING_STOCK',
    quantity_change: 35,
    unit_cost: 3.50,
    total_cost: 122.50,
    reason: 'Eco goods intake',
    created_at: '2026-08-01T08:00:00Z',
  },
  {
    id: 'led_008',
    organization_id: 'org_01',
    store_id: 'store_01',
    store_name: 'SuperMart Downtown Flagship',
    product_id: 'prod_08',
    product_name: 'Ultra Eco Laundry Detergent Sheets (60 ct)',
    sku: 'ECO-DET-08',
    movement_type: 'OPENING_STOCK',
    quantity_change: 28,
    unit_cost: 6.20,
    total_cost: 173.60,
    reason: 'Detergent shipment intake',
    created_at: '2026-08-01T08:00:00Z',
  },
  {
    id: 'led_009',
    organization_id: 'org_01',
    store_id: 'store_01',
    store_name: 'SuperMart Downtown Flagship',
    product_id: 'prod_09',
    product_name: 'Imported White Truffle Infused Tonic (Case of 12)',
    sku: 'BEV-TRF-09',
    movement_type: 'OPENING_STOCK',
    quantity_change: 48, // DEAD STOCK: 48 cases * $38 = $1,824 tied up capital!
    unit_cost: 38.00,
    total_cost: 1824.00,
    reason: 'Imported luxury beverage batch received 75 days ago',
    created_at: '2026-06-05T10:00:00Z',
  },
  // SuperMart Midtown (store_02)
  {
    id: 'led_010',
    organization_id: 'org_01',
    store_id: 'store_02',
    store_name: 'SuperMart Midtown Express',
    product_id: 'prod_01',
    product_name: 'Organic Honeycrisp Apples (1 lb)',
    sku: 'ORG-APL-01',
    movement_type: 'OPENING_STOCK',
    quantity_change: 50,
    unit_cost: 1.80,
    total_cost: 90.00,
    reason: 'Midtown branch opening count',
    created_at: '2026-08-01T08:00:00Z',
  },
  {
    id: 'led_011',
    organization_id: 'org_01',
    store_id: 'store_02',
    store_name: 'SuperMart Midtown Express',
    product_id: 'prod_06',
    product_name: 'Nitro Cold Brew Coffee Can (12 oz)',
    sku: 'BEV-CBR-06',
    movement_type: 'OPENING_STOCK',
    quantity_change: 140, // Surplus at Midtown! Can be transferred to Downtown!
    unit_cost: 1.90,
    total_cost: 266.00,
    reason: 'Midtown beverage delivery',
    created_at: '2026-08-01T08:00:00Z',
  },
];

export const INITIAL_SALES_ORDERS: SalesOrder[] = [
  {
    id: 'ord_1001',
    organization_id: 'org_01',
    store_id: 'store_01',
    store_name: 'SuperMart Downtown Flagship',
    customer_id: 'cust_01',
    customer_name: 'Alice Johnson',
    cashier_id: 'user_sales',
    cashier_name: 'David Miller',
    invoice_number: 'INV-202608-1001',
    subtotal: 34.65,
    tax_amount: 2.86,
    discount_amount: 0.00,
    total_amount: 37.51,
    cogs_amount: 16.70,
    payments: [
      {
        id: 'pay_01',
        sales_order_id: 'ord_1001',
        payment_method: 'SPLIT',
        amount: 37.51,
        reference_transaction_id: 'SPLIT-CASH-20.00-CARD-17.51',
        created_at: '2026-08-20T14:30:00Z',
      },
    ],
    items: [
      {
        id: 'item_01',
        sales_order_id: 'ord_1001',
        product_id: 'prod_01',
        product_name: 'Organic Honeycrisp Apples (1 lb)',
        sku: 'ORG-APL-01',
        quantity: 3,
        unit_cost: 1.80,
        unit_price: 3.99,
        subtotal: 11.97,
        cogs: 5.40,
      },
      {
        id: 'item_02',
        sales_order_id: 'ord_1001',
        product_id: 'prod_03',
        product_name: 'Grass-Fed Whole Milk 1 Gallon',
        sku: 'DRY-MLK-03',
        quantity: 2,
        unit_cost: 3.10,
        unit_price: 5.89,
        subtotal: 11.78,
        cogs: 6.20,
      },
      {
        id: 'item_03',
        sales_order_id: 'ord_1001',
        product_id: 'prod_05',
        product_name: 'San Francisco Sourdough Boule',
        sku: 'BAK-SRD-05',
        quantity: 1,
        unit_cost: 2.50,
        unit_price: 6.49,
        subtotal: 6.49,
        cogs: 2.50,
      },
      {
        id: 'item_04',
        sales_order_id: 'ord_1001',
        product_id: 'prod_06',
        product_name: 'Nitro Cold Brew Coffee Can (12 oz)',
        sku: 'BEV-CBR-06',
        quantity: 1,
        unit_cost: 1.90,
        unit_price: 4.29,
        subtotal: 4.29,
        cogs: 1.90,
      },
    ],
    status: 'COMPLETED',
    created_at: '2026-08-20T14:30:00Z',
  },
  {
    id: 'ord_1002',
    organization_id: 'org_01',
    store_id: 'store_01',
    store_name: 'SuperMart Downtown Flagship',
    customer_id: 'cust_02',
    customer_name: 'Benjamin Wright',
    cashier_id: 'user_sales',
    cashier_name: 'David Miller',
    invoice_number: 'INV-202608-1002',
    subtotal: 42.76,
    tax_amount: 3.53,
    discount_amount: 5.00,
    total_amount: 41.29,
    cogs_amount: 19.30,
    payments: [
      {
        id: 'pay_02',
        sales_order_id: 'ord_1002',
        payment_method: 'CREDIT_CARD',
        amount: 41.29,
        reference_transaction_id: 'TXN-CC-884920',
        created_at: '2026-08-20T16:15:00Z',
      },
    ],
    items: [
      {
        id: 'item_05',
        sales_order_id: 'ord_1002',
        product_id: 'prod_04',
        product_name: 'Barista Organic Oat Milk (32 oz)',
        sku: 'DRY-OAT-04',
        quantity: 4,
        unit_cost: 2.40,
        unit_price: 4.79,
        subtotal: 19.16,
        cogs: 9.60,
      },
      {
        id: 'item_06',
        sales_order_id: 'ord_1002',
        product_id: 'prod_08',
        product_name: 'Ultra Eco Laundry Detergent Sheets (60 ct)',
        sku: 'ECO-DET-08',
        quantity: 1,
        unit_cost: 6.20,
        unit_price: 14.99,
        subtotal: 14.99,
        cogs: 6.20,
      },
      {
        id: 'item_07',
        sales_order_id: 'ord_1002',
        product_id: 'prod_06',
        product_name: 'Nitro Cold Brew Coffee Can (12 oz)',
        sku: 'BEV-CBR-06',
        quantity: 2,
        unit_cost: 1.90,
        unit_price: 4.29,
        subtotal: 8.58,
        cogs: 3.80,
      },
    ],
    status: 'COMPLETED',
    created_at: '2026-08-20T16:15:00Z',
  },
];

export const INITIAL_PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: 'po_01',
    organization_id: 'org_01',
    store_id: 'store_01',
    supplier_id: 'sup_01',
    supplier_name: 'Valley Organics Farm Direct',
    po_number: 'PO-2026-0089',
    status: 'RECEIVED',
    total_amount: 356.00,
    payment_status: 'OVERDUE', // Due < 48 hours or overdue! Triggers Supplier Payment Escalation
    payment_due_date: '2026-08-22',
    items: [
      {
        id: 'poi_01',
        purchase_order_id: 'po_01',
        product_id: 'prod_01',
        product_name: 'Organic Honeycrisp Apples (1 lb)',
        sku: 'ORG-APL-01',
        quantity_ordered: 100,
        quantity_received: 100,
        unit_cost: 1.80,
        subtotal: 180.00,
      },
      {
        id: 'poi_02',
        purchase_order_id: 'po_01',
        product_id: 'prod_02',
        product_name: 'Organic Hass Avocados (Pack of 4)',
        sku: 'ORG-AVC-02',
        quantity_ordered: 80,
        quantity_received: 80,
        unit_cost: 2.20,
        subtotal: 176.00,
      },
    ],
    notes: 'Seasonal organic fresh batch delivery with temperature log',
    created_at: '2026-08-05T10:00:00Z',
    updated_at: '2026-08-07T11:30:00Z',
  },
  {
    id: 'po_02',
    organization_id: 'org_01',
    store_id: 'store_01',
    supplier_id: 'sup_03',
    supplier_name: 'Artisan Roast & Beverage Co.',
    po_number: 'PO-2026-0094',
    status: 'SENT',
    total_amount: 285.00,
    payment_status: 'PENDING',
    payment_due_date: '2026-08-22', // Due in 24 hours! Triggers escalation
    items: [
      {
        id: 'poi_03',
        purchase_order_id: 'po_02',
        product_id: 'prod_06',
        product_name: 'Nitro Cold Brew Coffee Can (12 oz)',
        sku: 'BEV-CBR-06',
        quantity_ordered: 150,
        quantity_received: 0,
        unit_cost: 1.90,
        subtotal: 285.00,
      },
    ],
    notes: 'Urgent restock for Downtown cold brew rush',
    created_at: '2026-08-19T09:00:00Z',
    updated_at: '2026-08-19T09:30:00Z',
  },
];

export const INITIAL_EXPENSE_CATEGORIES: ExpenseCategory[] = [
  { id: 'expcat_01', organization_id: 'org_01', name: 'Store Rent & Property' },
  { id: 'expcat_02', organization_id: 'org_01', name: 'Electricity & Cold Storage Utilities' },
  { id: 'expcat_03', organization_id: 'org_01', name: 'Staff Salaries & Shift Overtime' },
  { id: 'expcat_04', organization_id: 'org_01', name: 'POS & Software Subscriptions' },
  { id: 'expcat_05', organization_id: 'org_01', name: 'Packaging & Biodegradable Bags' },
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'exp_01',
    organization_id: 'org_01',
    store_id: 'store_01',
    category_id: 'expcat_02',
    category_name: 'Electricity & Cold Storage Utilities',
    title: 'Commercial Refrigeration Power - Aug 2026',
    amount: 1450.00,
    expense_date: '2026-08-15',
    notes: 'Includes downtown cold room continuous cooling electricity bill',
    created_at: '2026-08-15T12:00:00Z',
  },
  {
    id: 'exp_02',
    organization_id: 'org_01',
    store_id: 'store_01',
    category_id: 'expcat_03',
    category_name: 'Staff Salaries & Shift Overtime',
    title: 'Floor Staff Bi-Weekly Payroll',
    amount: 4800.00,
    expense_date: '2026-08-15',
    notes: 'Store managers and cashier team bi-weekly wages',
    created_at: '2026-08-15T17:00:00Z',
  },
  {
    id: 'exp_03',
    organization_id: 'org_01',
    store_id: 'store_01',
    category_id: 'expcat_05',
    category_name: 'Packaging & Biodegradable Bags',
    title: 'Eco Bag Supply 5000 units',
    amount: 320.00,
    expense_date: '2026-08-18',
    notes: 'Recycled brown bags and thermal receipt paper rolls',
    created_at: '2026-08-18T10:00:00Z',
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust_01',
    organization_id: 'org_01',
    name: 'Alice Johnson',
    email: 'alice.johnson@gmail.com',
    phone: '+1 (555) 789-0123',
    loyalty_points: 350,
    total_spend: 1420.50,
    created_at: '2026-03-12T00:00:00Z',
  },
  {
    id: 'cust_02',
    organization_id: 'org_01',
    name: 'Benjamin Wright',
    email: 'bwright@corporate.org',
    phone: '+1 (555) 890-1234',
    loyalty_points: 120,
    total_spend: 540.00,
    created_at: '2026-04-05T00:00:00Z',
  },
  {
    id: 'cust_03',
    organization_id: 'org_01',
    name: 'Elena Gilbert',
    email: 'elena.g@artisan.io',
    phone: '+1 (555) 901-2345',
    loyalty_points: 580,
    total_spend: 2310.80,
    created_at: '2026-02-18T00:00:00Z',
  },
];

export const INITIAL_STOCK_TRANSFERS: StockTransfer[] = [
  {
    id: 'trf_01',
    organization_id: 'org_01',
    transfer_number: 'TRF-2026-0042',
    source_store_id: 'store_02',
    source_store_name: 'SuperMart Midtown Express',
    destination_store_id: 'store_01',
    destination_store_name: 'SuperMart Downtown Flagship',
    status: 'REQUESTED',
    requested_by: 'user_manager',
    notes: 'Emergency transfer of Nitro Cold Brews to meet weekend downtown rush',
    items: [
      {
        id: 'trfi_01',
        transfer_id: 'trf_01',
        product_id: 'prod_06',
        product_name: 'Nitro Cold Brew Coffee Can (12 oz)',
        sku: 'BEV-CBR-06',
        quantity_requested: 50,
        quantity_sent: 0,
        quantity_received: 0,
      },
    ],
    created_at: '2026-08-20T11:00:00Z',
    updated_at: '2026-08-20T11:00:00Z',
  },
];

export const INITIAL_PROMOTIONS: Promotion[] = [
  {
    id: 'promo_01',
    organization_id: 'org_01',
    title: 'Weekend Organic Harvest 15% Off',
    discount_percentage: 15,
    target_tier: 'VIP',
    valid_until: '2026-08-31',
    code: 'ORGANIC15',
  },
  {
    id: 'promo_02',
    organization_id: 'org_01',
    title: 'Cold Brew Morning Power 10% Off',
    discount_percentage: 10,
    target_tier: 'ALL',
    valid_until: '2026-09-15',
    code: 'NITRO10',
  },
];

export const INITIAL_ALERTS: SystemAlert[] = [
  {
    id: 'alt_01',
    organization_id: 'org_01',
    store_id: 'store_01',
    alert_type: 'LOW_STOCK',
    severity: 'CRITICAL',
    title: 'Low Stock Alert: Nitro Cold Brew Coffee (8 units remaining)',
    message: 'SKU BEV-CBR-06 is below the reorder point of 40 units at Downtown Flagship. Velocity: 14 units/day. Estimated stockout in 0.6 days.',
    is_read: false,
    action_url: '/inventory',
    created_at: '2026-08-21T06:00:00Z',
  },
  {
    id: 'alt_02',
    organization_id: 'org_01',
    store_id: 'store_01',
    alert_type: 'SUPPLIER_PAYMENT',
    severity: 'WARNING',
    title: 'Supplier Payment Due < 48 Hours: Artisan Roast ($285.00)',
    message: 'Purchase order PO-2026-0094 payment is due on 2026-08-22. Verify invoice receipt and authorize disbursement.',
    is_read: false,
    action_url: '/purchases',
    created_at: '2026-08-21T05:30:00Z',
  },
  {
    id: 'alt_03',
    organization_id: 'org_01',
    alert_type: 'DEAD_STOCK',
    severity: 'WARNING',
    title: 'Dead Capital Warning: Truffle Infused Tonic ($1,824.00 stagnant)',
    message: 'SKU BEV-TRF-09 has 0 sales in 75 days with 48 units in stock. Markdown liquidation plan generated.',
    is_read: false,
    action_url: '/ai-assistant',
    created_at: '2026-08-21T04:00:00Z',
  },
];
